### ISSUE TITLE
NotImplementedError: Multisession implementation does not support discrete index yet

### ISSUE THREAD

**Issue by isib462** [AdaptiveMotorControlLab/CEBRA#203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I wonder if it is possible to use discrete labels in the case of multiple-sessions? When test the multi-session mode using discrete label,there is an error.
And if add the code"discrete_label = [arr.astype(float) for arr in discrete_label]", it can run without error(in continuous label mode,I think). So it seems that it cannot apply to discrete labels in multisession? Looking forward to your reply. thank you!

### Operating System

Ubuntu22.04

### CEBRA version

cebra                     0.4.0                    pypi_0    pypi

### Device type

gpu

### Steps To Reproduce

"timesteps1 = 5000
timesteps2 = 3000
neurons1 = 50
neurons2 = 30
out_dim = 8

neural_session1 = np.random.normal(0,1,(timesteps1, neurons1))
neural_session2 = np.random.normal(0,1,(timesteps2, neurons2))
neural_session=[neural_session1, neural_session2]
discrete_label1 = np.random.randint(0,10,(timesteps1, ))
discrete_label2 = np.random.randint(0,10,(timesteps2, ))
discrete_label=[discrete_label1,discrete_label2]
multi_cebra_model_discrete = cebra.CEBRA(model_architecture='offset10-model',
                    batch_size=512,
                    learning_rate=3e-4,
                    temperature=1,
                    output_dimension=3,
                    max_iterations=1000,
                    distance='cosine',
                    conditional='time_delta',
                    device='cuda_if_available',
                    verbose=True,
                    time_offsets=10)
multi_cebra_model_discrete.fit(neural_session, discrete_label)"

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/cebra/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-48-9a160d5da05e>", line 20, in <module>
    multi_cebra_model_discrete.fit(neural_session, discrete_label)
  File "/home/user/anaconda3/envs/cebra/lib/python3.9/site-packages/cebra/integrations/sklearn/cebra.py", line 1193, in fit
    self.partial_fit(X,
  File "/home/user/anaconda3/envs/cebra/lib/python3.9/site-packages/cebra/integrations/sklearn/cebra.py", line 1098, in partial_fit
    self.state_ = self._prepare_fit(X, *y)
  File "/home/user/anaconda3/envs/cebra/lib/python3.9/site-packages/cebra/integrations/sklearn/cebra.py", line 886, in _prepare_fit
    dataset, is_multisession = self._prepare_data(X, y)
  File "/home/user/anaconda3/envs/cebra/lib/python3.9/site-packages/cebra/integrations/sklearn/cebra.py", line 647, in _prepare_data
    dataset = _get_dataset_multi(X, y)
  File "/home/user/anaconda3/envs/cebra/lib/python3.9/site-packages/cebra/integrations/sklearn/cebra.py", line 638, in _get_dataset_multi
    return cebra.data.DatasetCollection(*[
  File "/home/user/anaconda3/envs/cebra/lib/python3.9/site-packages/cebra/data/datasets.py", line 225, in __init__
    raise NotImplementedError(
NotImplementedError: Multisession implementation does not support discrete index yet.
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/daptiveMotorControlLab/CEBRA/blob/main/CODE_OF_CONDUCT.md)

**Comment by MMathisLab** [comment]
Hi @isib462 thanks for your feature request; indeed this is not currently supported (we don't show this in the paper), but knowing it's useful to a user is helpful for us to prioritize feature requests (or please feel free to implement and we are happy to review your code).

**Comment by stes** [comment]
Hi @isib462 adding to that, we recently merged a feature for this (https://github.com/AdaptiveMotorControlLab/CEBRA/pull/135), could you check out whether the latest CEBRA version in the main branch covers your desired usecase?

**Comment by MMathisLab** [comment]
to pip install from the main branch `pip install "git+https://github.com/AdaptiveMotorControlLab/CEBRA.git"`
